#!/usr/bin/env python3
"""Build Geo3K refocus-style multiturn profiling datasets.

The parquet still contains the original Geo3K prompt and image. The multiturn
refocus image is generated by the rollout agent at runtime so GRPO branches can
share the same row while producing turn1 image reuse opportunities.
"""

from __future__ import annotations

import argparse
import copy
import os
from io import BytesIO
from pathlib import Path
from typing import Any

import pyarrow as pa
import pyarrow.parquet as pq
from PIL import Image


INSTRUCTION = (
    "You FIRST think about the reasoning process as an internal monologue and then provide the final answer. "
    "The reasoning process MUST BE enclosed within <think> </think> tags. "
    "The final answer MUST BE put in \\boxed{}."
)

VARIANT_CONFIGS = {
    "exact": {
        "scale": 1.0,
        "train_rows": 256,
        "test_rows": 64,
        "refocus_mode": "exact",
        "note": "Deterministic full-canvas highlight. Same row -> same turn1 refocus image.",
    },
    "diversified": {
        "scale": 1.0,
        "train_rows": 256,
        "test_rows": 64,
        "refocus_mode": "diversified",
        "note": "Same ROI with branch-dependent style/color. Similar but not byte-identical.",
    },
    "stress": {
        "scale": 2.0,
        "train_rows": 128,
        "test_rows": 32,
        "refocus_mode": "exact",
        "note": "Upscaled input plus deterministic full-canvas highlight to push E+P higher.",
    },
}


def image_item_to_pil(image_item: Any) -> Image.Image:
    if isinstance(image_item, dict):
        image_bytes = image_item.get("bytes")
        image_path = image_item.get("path")
        if image_bytes is not None:
            return Image.open(BytesIO(image_bytes)).convert("RGB")
        if image_path:
            return Image.open(image_path).convert("RGB")
    if isinstance(image_item, (bytes, bytearray)):
        return Image.open(BytesIO(image_item)).convert("RGB")
    if isinstance(image_item, str):
        return Image.open(image_item).convert("RGB")
    raise TypeError(f"Unsupported image item type: {type(image_item)!r}")


def pil_to_image_item(image: Image.Image) -> dict:
    buf = BytesIO()
    image.save(buf, format="PNG")
    return {"bytes": buf.getvalue(), "path": None}


def resize_image(image: Image.Image, scale: float) -> Image.Image:
    if abs(scale - 1.0) < 1e-6:
        return image.convert("RGB")
    width, height = image.size
    new_size = (max(1, int(round(width * scale))), max(1, int(round(height * scale))))
    resampling = getattr(Image, "Resampling", Image)
    return image.resize(new_size, resampling.BICUBIC).convert("RGB")


def prompt_content(row: dict, question: str) -> str:
    prompt = row.get("prompt") or []
    if prompt and isinstance(prompt, list):
        content = prompt[0].get("content", "")
        if isinstance(content, str) and content.strip():
            return content
    return f"<image>{question} {INSTRUCTION}"


def convert_row(row: dict, *, idx: int, split: str, variant: str, scale: float, refocus_mode: str) -> dict:
    row = copy.deepcopy(row)
    images = list(row.get("images") or [])
    if not images:
        raise ValueError("Geo3K row has no image")

    image = resize_image(image_item_to_pil(images[0]), scale)
    images = [pil_to_image_item(image)]
    extra = dict(row.get("extra_info") or {})
    reward_model = dict(row.get("reward_model") or {})
    question = str(extra.get("question") or "").strip()
    answer = str(extra.get("answer") or reward_model.get("ground_truth") or "").strip()

    extra.update(
        {
            "split": split,
            "index": idx,
            "answer": answer,
            "question": question,
            "geo3k_refocus_variant": variant,
            "geo3k_refocus_mode": refocus_mode,
            "geo3k_refocus_scale": float(scale),
            "geo3k_refocus_full_canvas": True,
            "geo3k_refocus_roi": "center",
            "geo3k_refocus_note": VARIANT_CONFIGS[variant]["note"],
            "need_tools_kwargs": False,
        }
    )

    return {
        "images": images,
        "data_source": "hiyouga/geometry3k",
        "prompt": [{"role": "user", "content": prompt_content(row, question)}],
        "ability": row.get("ability", "math"),
        "reward_model": {"style": "rule", "ground_truth": answer},
        "agent_name": "geo3k_refocus_agent",
        "extra_info": extra,
    }


def iter_rows(src: str):
    parquet_file = pq.ParquetFile(src)
    for batch in parquet_file.iter_batches(batch_size=64):
        table = pa.Table.from_batches([batch])
        for idx in range(table.num_rows):
            yield {name: table.column(name)[idx].as_py() for name in table.column_names}


def convert_split(
    *,
    src: str,
    dst: str,
    split: str,
    variant: str,
    scale: float,
    refocus_mode: str,
    max_rows: int,
) -> int:
    rows = []
    for idx, row in enumerate(iter_rows(src)):
        if len(rows) >= max_rows:
            break
        rows.append(convert_row(row, idx=idx, split=split, variant=variant, scale=scale, refocus_mode=refocus_mode))
    if not rows:
        raise RuntimeError(f"No rows converted from {src}")
    os.makedirs(os.path.dirname(dst), exist_ok=True)
    pq.write_table(pa.Table.from_pylist(rows), dst)
    return len(rows)


def resolve_source_file(src_dir: str, split: str) -> str:
    path = os.path.join(src_dir, f"{split}.parquet")
    if os.path.isfile(path):
        return path
    if split == "test":
        train = os.path.join(src_dir, "train.parquet")
        if os.path.isfile(train):
            return train
    raise FileNotFoundError(path)


def build_variant(args: argparse.Namespace, variant: str) -> None:
    cfg = VARIANT_CONFIGS[variant]
    scale = args.scale if args.scale is not None else cfg["scale"]
    train_rows = args.max_train_rows if args.max_train_rows is not None else cfg["train_rows"]
    test_rows = args.max_test_rows if args.max_test_rows is not None else cfg["test_rows"]
    refocus_mode = args.refocus_mode or cfg["refocus_mode"]

    save_dir = Path(args.local_save_dir) / f"geo3k_refocus_{variant}"
    for split, cap in (("train", train_rows), ("test", test_rows)):
        src = resolve_source_file(args.src_dir, split)
        dst = save_dir / f"{split}.parquet"
        count = convert_split(
            src=src,
            dst=str(dst),
            split=split,
            variant=variant,
            scale=scale,
            refocus_mode=refocus_mode,
            max_rows=cap,
        )
        print(f"[{variant}] wrote {count} {split} rows -> {dst}")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--src_dir", default="data/geo3k", help="Directory with Geo3K train.parquet/test.parquet.")
    parser.add_argument("--local_save_dir", default="data", help="Parent output directory.")
    parser.add_argument("--variant", choices=["exact", "diversified", "stress", "all"], default="all")
    parser.add_argument("--scale", type=float, default=None, help="Override image scale for all selected variants.")
    parser.add_argument("--refocus_mode", choices=["exact", "diversified"], default=None)
    parser.add_argument("--max_train_rows", type=int, default=None)
    parser.add_argument("--max_test_rows", type=int, default=None)
    args = parser.parse_args()

    variants = list(VARIANT_CONFIGS) if args.variant == "all" else [args.variant]
    for variant in variants:
        build_variant(args, variant)


if __name__ == "__main__":
    main()
