#!/usr/bin/env bash
# Step 1: prepare Sokoban workload for verl-agent.
#
# NOTE: Sokoban is NOT a static HF dataset. Levels are procedurally generated by
# gym_sokoban at env reset. The parquet files here are placeholders (verl-agent
# convention) to declare visual modality + batch size — same as upstream
# examples/grpo_trainer/run_sokoban.sh.
#
# Usage (from repo root or anywhere):
#   bash verl_vision/examples/profile/workloads/sokoban/prepare_sokoban_data.sh

set -euo pipefail

VERL_AGENT_ROOT="${VERL_AGENT_ROOT:-/workspace/repo/verl-agent}"
TRAIN_SIZE="${TRAIN_SIZE:-64}"
VAL_SIZE="${VAL_SIZE:-64}"
DATA_ROOT="${DATA_ROOT:-/data/verl-agent_sokoban}"

echo "[prepare] VERL_AGENT_ROOT=${VERL_AGENT_ROOT}"
echo "[prepare] DATA_ROOT=${DATA_ROOT} train=${TRAIN_SIZE} val=${VAL_SIZE}"

cd "${VERL_AGENT_ROOT}"

# Sokoban runtime deps — must live in the SAME conda env used for rollout (Ray workers
# do not reliably see ~/.local user-site packages).
PYTHON="${PYTHON:-python3}"
"${PYTHON}" - <<'PY'
import importlib.util
import os
import sys

checks = (
    ("gym", "gym"),
    ("gym_sokoban", "gym_sokoban"),
    ("matplotlib", "matplotlib"),
)
missing = [pip_name for pip_name, import_name in checks if importlib.util.find_spec(import_name) is None]
if missing:
    py = sys.executable
    raise SystemExit(
        f"Missing packages in {py}: {', '.join(missing)}\n"
        "Install into your rollout conda env (e.g. verl_vision):\n"
        "  PYTHONNOUSERSITE=1 pip install gym==0.26.2 gym_sokoban==0.0.6 matplotlib 'setuptools<81'"
    )
if os.environ.get("PYTHONNOUSERSITE") != "1":
    print(f"warning: re-check with PYTHONNOUSERSITE=1 using the same python as rollout ({sys.executable})")
print("Sokoban deps OK:", ", ".join(p for p, _ in checks))
PY

mkdir -p "${DATA_ROOT}/visual"
python3 - <<PY
import os
import datasets

train_size = int("${TRAIN_SIZE}")
val_size = int("${VAL_SIZE}")
data_root = "${DATA_ROOT}/visual"
os.makedirs(data_root, exist_ok=True)

# Placeholder parquet (verl-agent convention): modality + batch size only.
# Sokoban levels are generated at env reset, not read from parquet images.
src = datasets.load_dataset("hiyouga/geometry3k")
train_ds = src["train"].select(range(train_size))
test_ds = src["test"].select(range(val_size))

def make_map_fn(split):
    def process_fn(example, idx):
        example.pop("problem", None)
        images = example.pop("images")
        return {
            "data_source": "visual",
            "prompt": [{"role": "user", "content": "<image>"}],
            "images": images,
            "ability": "agent",
            "answer": ["0"],
            "reward_model": {"style": "rule", "ground_truth": "0"},
            "extra_info": {"split": split, "index": idx},
        }
    return process_fn

train_ds = train_ds.map(make_map_fn("train"), with_indices=True, num_proc=4)
test_ds = test_ds.map(make_map_fn("test"), with_indices=True, num_proc=4)
train_ds.to_parquet(os.path.join(data_root, "train.parquet"))
test_ds.to_parquet(os.path.join(data_root, "test.parquet"))
print("wrote", data_root)
PY

echo "[prepare] wrote:"
ls -la "${DATA_ROOT}/visual/"
